---
- name: install devel packages
  with_items: "{{ devel_packages }}"
  pkgng:
    name: "{{ item.name }}"
    state: present

- name: configure ccache system wide
  template:
    src: csh.cshrc.j2
    dest: /etc/csh.cshrc
